config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses, except: :delete
    resources :reviews, only: [:new, :create]
  end
  delete 'doses/:id', to: 'doses#destroy', as: :delete_dose
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  has_many :doses, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true

  def average_rating
    sum = 0

    reviews.each do |review|
      sum += review.rating unless review.rating.nil?
    end
    if sum.fdiv(reviews.length).nan?
      ''
    else
      sum.fdiv(reviews.length).fdiv(0.5).ceil * 0.5
    end
  end

  def stars
    average_rating == '' ? 0 : average_rating.floor
  end

  def half_star
    average_rating == '' ? '' : !(average_rating % 1 == 0)
  end
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates_uniqueness_of :cocktail, scope: :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :rating, :from, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new
    @review = Review.new
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktails_path
    else
      render :new
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      @review = Review.new
      render 'cocktails/show'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      @dose = Dose.new
      render 'cocktails/show'
    end
  end

  def review_params
    params.require(:review).permit(:comment, :rating, :from)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%), url(<%= asset_path 'bar.jpg' %>);">
  <div class="banner-content">
    <h1>The Martini</h1>
  </div>
</div>
</div>
<h1 class="text-center">Signature Cocktails</h1>
<div class="cards-container">
  <div class="container">
    <div class="row">
      <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-6">
        <!-- insert <div class="card"> -->
        <div class="card">
          <div class="card-img" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cocktail.photo.to_s == '' ? 'http://res.cloudinary.com/dzk8zzmdo/image/upload/v1541831609/fhj3o5ffjyhaexzdxuqa.jpg' : cocktail.photo %>);">
          </div>
          <div class="card-content">
            <div class="card-content-top">
              <h2 class="card-content-header">
                <%= link_to cocktail.name, cocktail_path(cocktail) %>
              </h2>
              <p class="card-content-ingredients">
                <% cocktail.ingredients.each_with_index do |ingredient, index| %>
                <% if index == cocktail.ingredients.length - 1 %>
                <%= ingredient.name  %>
                <% else %>
                <%= ingredient.name + "," %>
                <% end %>
                <% end %>
              </p>
              <div class="more-details">
                <%= link_to cocktail_path(cocktail) do %>
                <i class="fas fa-info-circle"></i> more details
                <% end %>
              </div>
            </div>
            <div class="card-content-bottom">
              <% cocktail.stars.times do %>
              <i class="fas fa-star"></i>
              <% end %>
              <% if cocktail.half_star == true %>
              <i class="fas fa-star-half"></i>
              <% end %>
              <%= cocktail.average_rating  %>
              (
              <%= cocktail.reviews.length  %> reviews)
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="form">
    <h1>Add a new cocktail</h1>
    <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name, required: false%>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= button_tag( :class => "button") do %>
    <i class="fas fa-plus-circle"></i> Add Cocktail
    <% end %>
    <% end %>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="page-container">
    <div class="title">
      <h1>
      <%= link_to cocktails_path do %>
        <i class="fas fa-undo-alt"></i>
        <% end %>
      <%= @cocktail.name %>
      </h1>
    </div>
    <hr>
    <div class="cocktail-container">
      <div class="cocktail-picture">
        <% if @cocktail.photo.to_s == "" %>
        <%= cl_image_tag("fhj3o5ffjyhaexzdxuqa", height: 400, width: 350, crop: :fill) %>
        <% else %>
        <%= cl_image_tag @cocktail.photo, height: 400, width: 350, crop: :fill %>
        <% end %>
      </div>
      <div class="cocktail-info">
        <div class="recipe">
          <h3>
          Recipe
          </h3>
          <ul>
            <% @cocktail.doses.each do |dose| %>
            <li>
              <%=dose.description + " | " + dose.ingredient.name%>
              <%= link_to delete_dose_path(dose), method: :delete do %>
              <i class="far fa-trash-alt" style="color: rgb(50,50,50)"></i>
              <% end %>
            </li>
            <% end %>
          </ul>
        </div>
        <div class="options">
          <%= simple_form_for [@cocktail, @dose] do |f| %>
          <%= f.input :description, placeholder: '1 Teaspoon' %>
          <%= f.association :ingredient, collection: Ingredient.order(:name), label_method: :name, value_method: :id, required: false %>
          <%= button_tag( :class => "button") do %>
          <i class="fas fa-plus-circle"></i> Add Recipe Line
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <hr>
    <div class="reviews">
      <h3>
        Reviews
        <% @cocktail.stars.times do %>
        <i class="fas fa-star"></i>
        <% end %>
        <% if @cocktail.half_star == true %>
        <i class="fas fa-star-half"></i>
        <% end %>
        <%= @cocktail.average_rating  %>
        (
        <%= @cocktail.reviews.length  %> reviews)
      </h3>
      <div class="cards-container">
        <div class="row">
          <% @cocktail.reviews.each do |review| %>
          <div class="col-xs-12 col-sm-6">
            <div class="card-review">
              <div class="stars">
                <% review.rating.times do %>
                <i class="fas fa-star"></i>
                <% end %>
              </div>
              <div class="comment">
                <%= review.comment %>
                <%= review.from %>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
    <hr>
    <div class="add-review-form">
      <%= simple_form_for [@cocktail, @review] do |f| %>
      <%= f.input :comment, placeholder: 'Awesome cocktail!' %>
      <%= f.input :rating, collection: [1,2,3,4,5], required: false %>
      <%= f.input :from, placeholder: 'John Smith' %>
      <%= button_tag( class: "button") do %>
      <i class="fas fa-plus-circle"></i> Add a Review
      <% end %>
      <% end %>
    </div>
  </div>
</div>
<%= link_to "delete cocktail", cocktail_path(@cocktail), method: :delete, data: {confirm: "Are you sure you want to delete this cocktail?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>RailsMisterCocktail</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <head>
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Questrial" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <div class="navbar-wagon">
    <!-- Logo -->
    <div class="navbar-left">
      <div>
        <%= link_to image_tag("martini.png", class: 'navbar-logo'), cocktails_path %>
      </div>
      <div>
        The Martini
      </div>
    </div>
    <div>
    </div>
    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">
      <div class="navbar-wagon-item navbar-wagon-link">
        <%= link_to 'Home', cocktails_path%>
      </div>
      <div class="navbar-wagon-item navbar-wagon-link">
        <%= link_to 'Add New', new_cocktail_path%>
      </div><!-- Profile picture with dropdown list -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <img src="https://kitt.lewagon.com/placeholder/users/jehon11" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><a href="https://kitt.lewagon.com/alumni/jehon11">Jeremy's Profile</a></li>
          </ul>
        </div>
      </div>
    </div>
    <!-- Dropdown appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to 'Home', cocktails_path%>
          </li>
          <li>
            <%= link_to 'Add New', new_cocktail_path%>
          </li>
          <li><a href="https://kitt.lewagon.com/alumni/jehon11">Jeremy's Profile</a></li>
        </ul>
      </div>
    </div>
  </div>
  <%= yield %>
  <%= javascript_include_tag "application" %>
  <!-- from app/assets/javascripts/application.js -->
  <%= javascript_pack_tag "application" %>
  <!-- from app/javascript/packs/application.js -->
</body>

</html>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>